# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unic < Formula
  desc "Go-based TUI tool for browsing and managing AWS resources in the terminal"
  homepage "https://github.com/DevopsArtFactory/unic"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DevopsArtFactory/unic/releases/download/v0.1.2/unic-darwin-amd64.tar.gz"
      sha256 "11776bfef2ad5e54c744d0fecdbd0daf156353bc42a7a5992da27f07024f4957"

      define_method(:install) do
        bin.install "unic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DevopsArtFactory/unic/releases/download/v0.1.2/unic-darwin-arm64.tar.gz"
      sha256 "12feba61d9a127897d3b7428f1464422f0f64ae52ff352f1e9df5155ba6afb9e"

      define_method(:install) do
        bin.install "unic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DevopsArtFactory/unic/releases/download/v0.1.2/unic-linux-amd64.tar.gz"
      sha256 "7a931707fb4c92cbf843959a3808c1bcffc448bc9559adb8a10ab46ef1855b30"
      define_method(:install) do
        bin.install "unic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DevopsArtFactory/unic/releases/download/v0.1.2/unic-linux-arm64.tar.gz"
      sha256 "0c8b0ce1740327f92efa64db45109389ef33f9e74819646d03e8a72a6ca58f36"
      define_method(:install) do
        bin.install "unic"
      end
    end
  end

  test do
    system "#{bin}/unic", "--version"
  end
end
