# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unic < Formula
  desc "Go-based TUI tool for browsing and managing AWS resources in the terminal"
  homepage "https://github.com/DevopsArtFactory/unic"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DevopsArtFactory/unic/releases/download/v0.2.3/unic-darwin-amd64.tar.gz"
      sha256 "f443a2f4c1963627816a1d4c24e829750f78fa453fcfbe16a2f38471ee270159"

      define_method(:install) do
        bin.install "unic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DevopsArtFactory/unic/releases/download/v0.2.3/unic-darwin-arm64.tar.gz"
      sha256 "1dacc7d8a477127f4951c5bd81351b13dec602fdd8515fa78ba6492cf1d21615"

      define_method(:install) do
        bin.install "unic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DevopsArtFactory/unic/releases/download/v0.2.3/unic-linux-amd64.tar.gz"
      sha256 "f4d66fd44ee7d9e90ac89ff75faffe48de8ae2abac1da430d2b32b4b77ed56a4"
      define_method(:install) do
        bin.install "unic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DevopsArtFactory/unic/releases/download/v0.2.3/unic-linux-arm64.tar.gz"
      sha256 "166c50f70acd86e447ea28c9524653f3d3b8cdd14bb758cec92b94de51010b17"
      define_method(:install) do
        bin.install "unic"
      end
    end
  end

  test do
    system "#{bin}/unic", "--version"
  end
end
